# Generated by Django 3.0.9 on 2020-08-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buscar',
            name='formato',
            field=models.CharField(default='Video', max_length=20),
        ),
        migrations.AddField(
            model_name='buscar',
            name='nombre',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='buscar',
            name='tamanno',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
